name: Deploy Backend

on:
push:
branches:
- main

jobs:
build-and-deploy:
runs-on: ubuntu-latest

```
permissions:
  id-token: write
  contents: read

steps:
  - name: Checkout
    uses: actions/checkout@v4

  - name: Setup Node
    uses: actions/setup-node@v4
    with:
      node-version: 22

  - name: Install Backend Dependencies
    run: |
      cd backend
      npm install

  - name: Build Backend
    run: |
      cd backend
      npm run build

  - name: Azure Login
    uses: azure/login@v2
    with:
      client-id: ${{ secrets.BACKEND_CLIENT_ID }}
      tenant-id: ${{ secrets.BACKEND_TENANT_ID }}
      subscription-id: ${{ secrets.BACKEND_SUBSCRIPTION_ID }}

  - name: Deploy Backend
    uses: azure/webapps-deploy@v3
    with:
      app-name: mmport-api
      package: ./backend
```
